[[redirects]]
  from = "https://magicconch-blog.netlify.app/*"
  to = "https://www.magicconch.top/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://magicconch.top/*"
  to = "https://www.magicconch.top/:splat"
  status = 301
  force = true  
[[redirects]]
  from = "https://blog.magicconch.top/*"
  to = "https://www.magicconch.top/:splat"
  status = 301
  force = true


# :splat 是为了原路径保持，不然会跳转到主页  